### ISSUE TITLE
IDEA: use regex syntax {n} instead of ...n...

### ISSUE THREAD

**Issue by nguyenxndaidev** [kwonoj/rx-sandbox#67]
Don't you think the regex syntax {n} is better than ...n...?
The current ...n... can only simulate n of dashes. But if we use {n} we can have:

```
const = 'a-{8}b'; // 'a--------b'
const = 'a{8}b'; // 'aaaaaaaab'
```

**Comment by kwonoj** [comment]
No, I'm not. token . is specifically designed to support long timeframe in marble instead of generic repeat purpose. . itself is very limited usage token and only except it marble string should be readable without additional translations for shortened tokens. For value tokens I'd prefer explicity unless there are cases can't be represented. In most cases if value requires huge repeat similar to long running timeframe, test case itself need to be redesigned.
